### ISSUE TITLE
Add link in this projects README and on perk homepage to request slack access

### ISSUE THREAD

**Issue by alarner** [alarner/perk-docs#45]
Here's a link to the request form 

https://docs.google.com/forms/d/e/1FAIpQLSeKAZfd_H0fyYTEr_cbrhK1RTWgn0cBr0iRdc2WEZ89WgFCCg/viewform?c=0&w=1

**Comment by rampatra** [comment]
PR raised: https://github.com/alarner/perk-docs/pull/46

**Comment by ramswaroop** [comment]
https://github.com/alarner/perk-docs/pull/46

**Comment by akanksha1590** [comment]
@alarner - Can I start working on this?

**Comment by alarner** [comment]
@akanksha1590 looks like @ramswaroop is already on this one. I'd love help with any of the other outstanding issues though!
