### ISSUE TITLE
Asked to use knex in video 3, but it was never installed

### ISSUE THREAD

**Issue by m2mathew** [alarner/perk-docs#51]
In the [3rd video](http://perkframework.com/v1/video-reel/03-database-migrations-creating-tables.html), the user is asked to use the command `knex migrate:make create_links`, but it was never installed via these videos.

Way back in the [1st video](http://perkframework.com/v1/video-reel/01-up-and-running.html), the user is asked to visit [this page](http://perkframework.com/v1/guides/install-node-redis-and-postgres-on-your-mac.html) to install **node**, **redis**, and **postgres**. Later in the video the user is asked to type `npm install -g perk-cli` to install the perk command line tools.

The "[Getting Starting with Perk on OS X](http://perkframework.com/v1/guides/getting-started-os-x.html)" guide does have the user install **knex** globally using the command `npm install -g knex perk-cli`. This fixed my glitch.

Should this command also be included in the video or at least on the links below video 1?

**Comment by alarner** [comment]
Great catch @m2mathew. I've added an annotation to the video to make it clear that you should also install knex.
